from setuptools import setup

setup(name="moses",
      version="0.0.1",
      packages = ['moses'],
      py_modules = [],
      entry_points = {'console_scripts':['moses_dbd_server = moses.__main__:script_moses_dbd_server',
                                         'moses_dbd_client = moses.__main__:script_moses_dbd_client',
                                         'transfer_to_coriolis = moses.__main__:script_coriolis_upload',
                                         'convert_for_coriolis = moses.__main__:script_convert_for_coriolis'],
                      'gui_scripts':[]},
      install_requires = 'numpy dbdreader arrow zmq aionotify'.split(),
      author="Lucas Merckelbach",
      author_email="lucas.merckelbach@hzg.de",
      description="",
      long_description="""""",
    url='',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Console',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
        'Operating System :: MacOS :: MacOS X',
                  'Operating System :: Microsoft :: Windows',
        'Operating System :: POSIX',
        'Programming Language :: Python',
        'Topic :: Scientific/Engineering',
    ])
