# DATA blocks for Coriolis database
from collections import namedtuple

FTP_Credentials = namedtuple('FTP_Credentials', 'host user password rootdir'.split())

CREDENTIALS = dict(coriolis = FTP_Credentials('eftp.ifremer.fr',
                                              'lm20516',
                                              '0W285WgN',
                                              'submit'),
                   debug = FTP_Credentials('ftp.hzg.de',
                                           '',
                                           'my@org.net',
                                           'incoming/merckelb'))

# DO NOT specify m_present_time as parameter. It then ends up twice....

PARAMETERS = dict(amadeus = ['m_depth',
                             'm_gps_lat',
                             'm_gps_lon',
                             'm_water_vx',
                             'm_water_vy',
                             'sci_flntu_chlor_units',
                             'sci_flntu_turb_units',
                             'sci_m_present_time',
                             'sci_water_cond',
                             'sci_water_pressure',
                             'sci_water_temp'],
                  sebastian = [ 'm_depth',
                                'm_gps_lat',
                                'm_gps_lon',
                                'm_water_vx',
                                'm_water_vy',
                                'sci_bb3slo_b470_scaled',
                                'sci_bb3slo_b532_scaled',
                                'sci_bb3slo_b660_scaled',
                                'sci_flbbcd_bb_units',
                                'sci_flbbcd_cdom_units',
                                'sci_flbbcd_chlor_units',
                                'sci_m_present_time',
                                'sci_water_cond',
                                'sci_water_pressure',
                                'sci_water_temp'],
                  comet = ['m_depth',
                           'm_gps_lat',
                           'm_gps_lon',
                           'm_water_vx',
                           'm_water_vy',
                           'sci_flntu_chlor_units',
                           'sci_flntu_turb_units',
                           'sci_m_present_time',
                           'sci_water_cond',
                           'sci_water_pressure',
                           'sci_water_temp'],
                  dipsy = ['m_depth',
                           'm_gps_lat',
                           'm_gps_lon',
                           'm_water_vx',
                           'm_water_vy',
                           'sci_flbbcd_chlor_units',
                           'sci_flbbcd_bb_units',
                           'sci_flbbcd_cdom_units',
                           'sci_m_present_time',
                           'sci_oxy4_oxygen',
                           'sci_water_cond',
                           'sci_water_pressure',
                           'sci_water_temp'],
                  sim = ['m_depth',
                         'm_roll'])
